output: problem5main.o problem5char.o problem5lines.o problem5words.o
	gcc problem5main.o problem5char.o problem5lines.o problem5words.o -o problem5output

problem5main.o:
	gcc -c problem5main.c
	
problem5char.o:
	gcc -c problem5char.c

problem5lines.o:
	gcc -c problem5lines.c

problem5words.o:
	gcc -c problem5words.c

clean:
	rm *.o problem5output